export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  // QuickBooks
  qbClientId:       process.env.QUICKBOOKS_CLIENT_ID       ?? "",
  qbClientSecret:   process.env.QUICKBOOKS_CLIENT_SECRET   ?? "",
  qbEnvironment:    (process.env.QUICKBOOKS_ENVIRONMENT    ?? "sandbox") as "sandbox" | "production",
  qbRedirectUri:    process.env.QUICKBOOKS_REDIRECT_URI    ?? "",
  qbRealmId:        process.env.QUICKBOOKS_REALM_ID        ?? "",
  qbRefreshToken:   process.env.QUICKBOOKS_REFRESH_TOKEN   ?? "",
  // Twilio
  twilioAccountSid:          process.env.TWILIO_ACCOUNT_SID             ?? "",
  twilioAuthToken:           process.env.TWILIO_AUTH_TOKEN              ?? "",
  twilioWhatsappFrom:        process.env.TWILIO_WHATSAPP_FROM           ?? "",
  twilioWhatsappNumber:      process.env.TWILIO_WHATSAPP_NUMBER         ?? "",
  twilioWhatsappTemplateSid: process.env.TWILIO_WHATSAPP_TEMPLATE_SID   ?? "",
  twilioMessagingServiceSid: process.env.TWILIO_MESSAGING_SERVICE_SID   ?? "",
  appBaseUrl: process.env.APP_BASE_URL ?? "https://primerewds.com",
};
